version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/boardup-py
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/install_requirements.sh
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
