version: '3'

services:

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file: .env


  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    env_file: .env