# Generated by Django 3.0.8 on 2020-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
    ]
