# Generated by Django 3.0.8 on 2020-08-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200805_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='survey.Question'),
        ),
    ]
