# Generated by Django 3.0.8 on 2020-08-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200809_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('interview_id', 'question_id')},
        ),
    ]
